#!/usr/bin/env python3
"""Render docs/device-results.md from the JSON files under results/.

    harness/report.py

Every table is built from the stored results, so rerunning the harness and
this script reproduces the document.
"""

import json
import pathlib
import statistics

ROOT = pathlib.Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
OUT = ROOT / "docs/device-results.md"


def load_runs():
    runs = []
    for folder in sorted(p for p in RESULTS.iterdir() if p.is_dir()):
        files = {f.stem: json.loads(f.read_text()) for f in folder.glob("*.json")}
        if not files:
            continue
        sample = next(iter(files.values()))
        device = sample.get("device", {})
        runs.append({
            "name": folder.name,
            "platform": sample.get("platform", "?"),
            "device": device,
            "build": sample.get("build", {}),
            "files": files,
        })
    return runs


def ms(value):
    if value is None:
        return "–"
    if value >= 1000:
        return f"{value / 1000:.2f} s"
    return f"{value:.0f} ms" if value >= 10 else f"{value:.1f} ms"


def size(n):
    if n is None:
        return "–"
    for unit, scale in (("GiB", 1 << 30), ("MiB", 1 << 20), ("KiB", 1 << 10)):
        if n >= scale:
            return f"{n / scale:.1f} {unit}"
    return f"{n} B"


MODELS = {"iPhone14,4": "iPhone 13 mini", "iPhone18,3": "iPhone 17"}


def device_label(run):
    d = run["device"]
    kind = "simulator" if run["platform"] == "ios" else "emulator"
    sim = f" ({kind})" if d.get("simulator") else " (device)"
    model = MODELS.get(d.get("model"), d.get("model", "?"))
    note = ", 256 MiB reservations, pool 5" if run["name"].endswith("256mib-reservation") else ""
    return f"{model}, {d.get('os', '?')}{sim}{note}"


def table(headers, rows):
    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    lines += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return "\n".join(lines)


def first_mark(result, prefix):
    for mark in result.get("timeline", []):
        if mark["event"].startswith(prefix):
            return mark["ms"]
    return None


def main():
    runs = load_runs()
    by_name = {r["name"]: r for r in runs}
    out = []
    out.append("# Device results\n")
    out.append("Generated by `harness/report.py` from `results/`. Every value comes from a stored run; "
               "rerun the harness and this script to reproduce the tables.\n")
    out.append("Runs cover a real iPhone 13 mini (iOS 27), the iOS Simulator and the Android emulator. No Android "
               "phone has run yet; the harness's `android-device` target runs the same scenarios when one is "
               "available.\n")

    # Runs
    rows = []
    for r in runs:
        b = r["build"]
        profiles = sorted({f.get("profile", "?") for f in r["files"].values()})
        rows.append([f"`{r['name']}`", device_label(r), b.get("target", "?"),
                     f"{b.get('core_version', '?')} `{b.get('core_revision', '?')[:12]}`", ", ".join(profiles),
                     len(r["files"])])
    out.append("## Runs\n")
    out.append(table(["Run", "Device", "Target", "Core", "Profiles", "Scenarios"], rows) + "\n")

    base = [r for r in runs if "conformance" in r["files"]]

    # Conformance
    out.append("## Wasm backend conformance\n")
    out.append("The fixture contract runs on every backend the target has. Each backend must return the "
               "expected bytes, turn out-of-bounds, divide-by-zero and unreachable traps into typed errors and keep "
               "working, stop an endless loop at the execution limit, and compile River's and Atlas's real "
               "contracts. Backends the target cannot run must be refused.\n")
    rows = []
    for r in base:
        c = r["files"]["conformance"]["result"]
        for backend in c["available_backends"] + [b for b in ("cranelift", "pulley") if b not in c["available_backends"]]:
            cases = [x for x in c["cases"] if x["backend"] == backend]
            if not cases:
                continue
            passed = sum(x["passed"] for x in cases)
            get = {x["name"]: x for x in cases}
            role = "refused" if "refuse_unavailable" in get else "runs"
            rows.append([device_label(r), backend, role, f"{passed}/{len(cases)}",
                         ms(get.get("compute", {}).get("elapsed_ms")),
                         ms(get.get("compile_river_room_contract", {}).get("elapsed_ms")),
                         ms(get.get("execution_limit", {}).get("elapsed_ms"))])
        shared = [x for x in c["cases"] if x["backend"] == "all"]
        for x in shared:
            rows.append([device_label(r), "all", x["name"], "1/1" if x["passed"] else "0/1", "–", "–", "–"])
    out.append(table(["Device", "Backend", "Role", "Cases passed", "Compute case", "River room contract compile",
                      "Execution limit"], rows) + "\n")

    # Fixtures
    out.append("## Shared protocol fixtures\n")
    out.append("Each run compares its values with `fixtures/protocol/protocol-fixtures.json`, written on desktop: "
               "request and reply encodings, results, typed errors, the result after a timed-out request, and "
               "callback order. The native route runs the same script through the Swift or Kotlin bindings.\n")
    rows = []
    for r in base:
        f = r["files"].get("fixtures", {}).get("result", {})
        n = r["files"].get("native", {}).get("result", {})
        checks = f.get("checks", [])
        native = n.get("checks", [])
        rows.append([device_label(r), f"{sum(c['passed'] for c in checks)}/{len(checks)}",
                     f"{sum(c['passed'] for c in native)}/{len(native)}"])
    out.append(table(["Device", "Rust fixtures matching desktop", "Swift/Kotlin route matching desktop"], rows) + "\n")

    # Startup and lifecycle
    out.append("## Startup and lifecycle\n")
    out.append("Cold start is a new process after `terminate`; process start comes from the kernel "
               "(`kinfo_proc` on iOS, `Process.getStartUptimeMillis` on Android). Node start covers settings, "
               "store, client API and node build. The lifecycle rows repeat stop and start three times, as the "
               "app does when it moves to the background and returns.\n")
    rows = []
    for r in base:
        s = r["files"].get("startup", {}).get("result", {})
        cycles = r["files"].get("lifecycle", {}).get("result", {}).get("cycles", [])
        am = r["files"].get("startup", {}).get("host", {}).get("am_start", {})
        rows.append([device_label(r), ms(s.get("process_to_first_frame_ms")),
                     ms(float(am["TotalTime"])) if am.get("TotalTime") else "–",
                     ms(s.get("node_first_start_ms")), ms(s.get("node_stop_ms")), ms(s.get("node_restart_ms")),
                     ms(statistics.median(c["start_ms"] for c in cycles)) if cycles else "–",
                     "yes" if cycles and all(c["fresh_session"] for c in cycles) else "–"])
    out.append(table(["Device", "Process to first frame", "Android launch (am start)", "Node start", "Node stop",
                      "Node restart", "Restart after background (median of 3)", "Fresh session each time"],
                     rows) + "\n")

    # Web apps
    out.append("## River and Atlas in the WebView\n")
    out.append("The node serves each app's website container at `http://127.0.0.1:<port>/v1/contract/web/<id>/`. "
               "Times run from the screen's first step. *Local* preloads the pinned container into an offline "
               "node; *test gateway* reads it through the isolated gateway on the Mac; *public* reads it from the "
               "live network after a fresh install. Traffic is the node's peer traffic during the load.\n")
    rows = []
    for r in runs:
        for app in ("river", "atlas"):
            f = r["files"].get(app)
            if not f:
                continue
            res = f.get("result", {})
            traffic = res.get("load_traffic") or {}
            fresh = f.get("harness", {}).get("fresh_install")
            profile = {"local": "local", "gateway": "test gateway", "public": "public"}.get(f.get("profile"), "?")
            rows.append([device_label(r), app.capitalize(), profile + (", fresh install" if fresh else ""),
                         ms(first_mark(res, "first_peer")), ms(first_mark(res, "shell_loaded")),
                         ms(first_mark(res, f"title:{app.capitalize()}")),
                         size(traffic.get("download_bytes")), size(traffic.get("upload_bytes"))])
    out.append(table(["Device", "App", "Profile", "First peer", "Shell page loaded", "App title shown",
                      "Downloaded", "Uploaded"], rows) + "\n")

    # Resume
    rows = []
    for r in runs:
        f = r["files"].get("resume-resume")
        if not f:
            continue
        res = f.get("result", {})
        after = {"timeline": res.get("after_resume", [])}
        rows.append([device_label(r), f.get("profile"), ms(first_mark(after, "node_running")),
                     ms(first_mark(after, "first_peer")), ms(first_mark(after, "title:River")),
                     res.get("session")])
    if rows:
        out.append("### Resume after another app\n")
        out.append("River is open; the harness opens another app for 20 s and then returns. Times run from the "
                   "moment the host logs its fresh session; a negative time means that step finished before the "
                   "log line.\n")
        out.append(table(["Device", "Profile", "Node running", "First peer", "River shown again", "Session"],
                         rows) + "\n")

    # Large records
    out.append("## Large-record copying, split by layer\n")
    out.append("*Bindings* is a round trip of the bytes through Swift or Kotlin and Rust with no node work. *Node* "
               "is measured in Rust from sending the request to its reply. The rest of each put or get is the "
               "bindings' copy of the record.\n")
    rows = []
    for r in base:
        n = r["files"].get("native", {}).get("result", {})
        for s in n.get("large_records", []):
            rows.append([device_label(r), size(s["bytes"]), ms(s["echoMs"]), ms(s["putMs"]), ms(s["putNodeMs"]),
                         ms(s["getMs"]), ms(s["getNodeMs"]), "yes" if s["intact"] else "no"])
    out.append(table(["Device", "Record", "Bindings round trip", "Put", "Put in node", "Get", "Get in node",
                      "Bytes intact"], rows) + "\n")

    # Throughput
    out.append("## Subscription throughput\n")
    out.append("One connection subscribes to a contract; another sends 200 updates of 64 bytes back to back. Each "
               "update notification carries the full state, which grows to 12.8 KB.\n")
    rows = []
    for r in base:
        t = r["files"].get("throughput", {}).get("result")
        if t:
            rows.append([device_label(r), t["received"], f"{t['updates_per_second']:.1f}", ms(t["receive_seconds"] * 1000),
                         size(t.get("notification_bytes"))])
    out.append(table(["Device", "Updates received", "Updates per second", "Total", "Notification bytes"], rows) + "\n")

    # Memory and storage
    out.append("## Memory, storage and address space\n")
    out.append("Footprint is `phys_footprint` on iOS (what the system uses to end apps) and PSS on Android, "
               "sampled every second for 20 s with River open offline. Address space counts every reserved "
               "region; on the Simulator the macOS host reserves about 400 GiB before the app runs.\n")
    rows = []
    for r in base:
        river = r["files"].get("river", {}).get("result", {})
        samples = river.get("memory_samples", [])
        foot = [s.get("footprint_bytes") for s in samples if s.get("footprint_bytes")]
        st = r["files"].get("storage", {}).get("result", {})
        wi = r["files"].get("wasm_instances", {}).get("result", {})
        rows.append([device_label(r),
                     f"{size(min(foot))} – {size(max(foot))}" if foot else "–",
                     size(samples[-1]["virtual_bytes"]) if samples else "–",
                     size(st.get("data_bytes")), size(st.get("cache_bytes")), size(st.get("logs_bytes")),
                     f"{wi.get('stored', '–')} stored, {size(wi.get('virtual_bytes_per_contract'))} each"
                     if wi else "–"])
    out.append(table(["Device", "Footprint with River open", "Address space", "Stores", "Unpacked web apps", "Logs",
                      "Contract stress (address space per contract)"], rows) + "\n")

    # Package size
    out.append("## Package size\n")
    rows = []
    for r in base:
        pkg = r["files"]["conformance"].get("harness", {}).get("package", {})
        if r["platform"] == "ios":
            kind = "simulator" if r["device"].get("simulator") else "device"
            rows.append([device_label(r), pkg.get("config"), f"App bundle {size(pkg.get('app_bytes'))} (unstripped {kind} build)"])
        else:
            abi = ", ".join(r["device"].get("abis", [])[:1])
            rows.append([device_label(r), pkg.get("config"), f"{abi} APK {size(pkg.get('apk_file_bytes'))}"])
    out.append(table(["Device", "Build", "Size"], rows) + "\n")
    sizes_file = RESULTS / "package-sizes.json"
    if sizes_file.exists():
        sizes = json.loads(sizes_file.read_text())
        out.append(f"Release packages measured {sizes['measured']}. {sizes['note']}\n")
        out.append(table(["Package", "Size"], [
            ["iOS app for devices", size(sizes["ios_device_release_app_bytes"])],
            ["iOS app for devices, stripped", size(sizes["ios_device_release_stripped_app_bytes"])],
            ["iOS zipped, before App Store thinning", size(sizes["ios_device_release_zipped_ipa_estimate_bytes"])],
            ["iOS bundled resources (containers, fixtures, test page)", size(sizes["ios_resources_bytes"])],
            ["Android APK, arm64-v8a", size(sizes["android_release_apk_arm64-v8a_bytes"])],
            ["Android APK, x86_64", size(sizes["android_release_apk_x86_64_bytes"])],
            ["Android APK, armeabi-v7a", size(sizes["android_release_apk_armeabi-v7a_bytes"])],
            ["Android APK, all three ABIs", size(sizes["android_release_apk_universal_bytes"])],
        ]) + "\n")

    # Network
    out.append("## Network tests\n")
    rows = []
    for r in runs:
        w = r["files"].get("watch")
        if w:
            t = w["result"]["traffic"]
            secs = w["result"]["seconds"]
            peers = max(s["peers"] for s in w["result"]["samples"])
            rows.append([device_label(r), f"idle, {w.get('profile')}", f"{secs} s", peers,
                         f"{size(t['upload_bytes'])} ({t['upload_bytes'] / secs / 1024:.1f} KiB/s)",
                         f"{size(t['download_bytes'])} ({t['download_bytes'] / secs / 1024:.1f} KiB/s)"])
        for key, label in (("watch-wifi-toggle", "Wi-Fi off 30 s (emulated cellular)"),
                           ("watch-offline", "all networks off")):
            w = r["files"].get(key)
            if not w:
                continue
            t = w["result"]["traffic"]
            secs = w["result"]["seconds"]
            hold = next((a for a in w["host"]["actions"] if "off" in a["action"]), None)
            peers = max(s["peers"] for s in w["result"]["samples"])
            rows.append([device_label(r), label + (" (90 s)" if "long" in r["name"] else ""), f"{secs} s", peers,
                         f"{size(t['upload_bytes'])} ({t['upload_bytes'] / secs / 1024:.1f} KiB/s)",
                         f"{size(t['download_bytes'])} ({t['download_bytes'] / secs / 1024:.1f} KiB/s)"])
    out.append(table(["Device", "Workload", "Duration", "Most peers", "Uploaded", "Downloaded"], rows) + "\n")

    # Guided network tests on a phone
    guided = [(r, r["files"][k]) for r in runs for k in ("transition", "offline_start", "cellular_start")
              if k in r["files"]]
    if guided:
        out.append("## Network changes on the iPhone\n")
        out.append("Guided on the phone's screen: the app asks the person holding it to change the network and "
                   "waits until iOS reports the new path. Samples come every second.\n")
        for r, f in guided:
            res = f.get("result", {})
            if f["scenario"] == "transition":
                samples = res.get("samples", [])
                def last(phase, key):
                    vals = [s[key] for s in samples if s["phase"] == phase]
                    return vals[-1] if vals else None
                def first(phase, key):
                    vals = [s[key] for s in samples if s["phase"] == phase]
                    return vals[0] if vals else None
                cell_down = (last("waiting_for_wifi", "download_bytes") or 0) - (first("cellular", "download_bytes") or 0)
                cell_up = (last("waiting_for_wifi", "upload_bytes") or 0) - (first("cellular", "upload_bytes") or 0)
                out.append(table(["Step", "Result"], [
                    ["Peers on Wi-Fi before the switch", last("waiting_for_cellular", "peers")],
                    ["Peers reported on cellular", last("cellular", "peers")],
                    ["Traffic during 90 s on cellular", f"{size(cell_down)} down, {size(cell_up)} up"],
                    ["Peers 18 s after Wi-Fi returned", last("wifi_again", "peers")],
                    ["Whole run", f"{size(res['traffic']['download_bytes'])} down, {size(res['traffic']['upload_bytes'])} up"],
                ]) + "\n")
            elif f["scenario"] == "offline_start":
                out.append(table(["Offline start", "Result"], [
                    ["Node start in Airplane Mode", "started" if res.get("offline_start_ok") else f"failed: {res.get('offline_start_error')}"],
                    ["Time to that answer", ms(res.get("offline_start_ms"))],
                    ["First peer after Airplane Mode off", ms(res.get("online_first_peer_ms"))],
                ]) + "\n")
            elif f["scenario"] == "cellular_start":
                t = res.get("cellular_traffic", {})
                out.append(table(["Fresh start on cellular", "Result"], [
                    ["Node start", ms(res.get("cellular_start_ms")) if res.get("cellular_start_ok") else f"failed: {res.get('cellular_start_error')}"],
                    ["First peer through the carrier's NAT", ms(res.get("cellular_first_peer_ms"))],
                    ["Traffic over the next 30 s", f"{size(t.get('download_bytes'))} down, {size(t.get('upload_bytes'))} up"],
                ]) + "\n")

    # Alerts and bridge
    out.append("## Message alerts and the bridge\n")
    rows = []
    for r in base:
        a = r["files"].get("alerts", {}).get("result", {})
        b = r["files"].get("bridge", {}).get("result", {})
        ping = b.get("pingMs", {})
        rows.append([device_label(r), "yes" if a.get("opened") else "–", ms(a.get("raise_to_banner_ms")),
                     f"{sum(c['passed'] for c in b.get('checks', []))}/{len(b.get('checks', []))}",
                     f"{ping['p50']:.1f} ms / {ping['p95']:.1f} ms" if ping else "–"])
    out.append(table(["Device", "Alert tap reached the page", "Page to banner", "Bridge checks",
                      "Bridge round trip (median / p95)"], rows) + "\n")

    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
